### ISSUE TITLE
Dialog Systems Milestone 1

### ISSUE THREAD

**Issue by blkilpatrick42** [blkilpatrick42/Jim#1]
Dialog system for talking to NPCs 
- [X] Passive monologue (player passing NPCs)
- [x] Visual novel styled dialog with 2 or more characters
- [x] fix font for character speech

**Comment by blkilpatrick42** [comment]
Added initial passive monologue code

**Comment by blkilpatrick42** [comment]
https://forum.godotengine.org/t/how-to-load-txt-files/641/2

Could use this to load text files for large amounts of text.

**Comment by blkilpatrick42** [comment]
BLOCK_DEF
	#File is composed of "block states" which are defined to be
	#read in code by a file reader in the NPC script
	#which has a "block reader" fn which gobbles up these blocks
	#and translates them into NPC actions ingame
/BLOCK_DEF

#PRIMITIVE NON NESTED EXAMPLES (appear as lone root def, or part of advanced def):

#example for existing "Alert Passive" directive
ALERT_PASSIVE 
	passive_text: "Example passive text"
	talk_radius: 50
/ALERT_PASSIVE

FULL_PASSIVE
	facing_direction: right
/FULL_PASSIVE

#concept for shop def
SHOP
	ITEM(name,price)
	ITEM(name,price)
	ITEM(name,price)
/SHOP

#ADVANCED NESTED EXAMPLES (nested defs contain nested primitive defs):

SCHEDULED
	0:
	ALERT_PASSIVE
		passive_text: "It sure is midnight"
		talk_radius: 50
	/ALERT_PASSIVE
	11:
	ALERT_PASSIVE
		passive_text: "It is now noon"
		talk_radius: 50
	/ALERT_PASSIVE
	12:
	PASSIVE_WANDER
		passive_text: "Excuse me"
		talk_radius: 50
		wander_distance: 500 #distance in pixels? 
		stop_at_boundaries: true
	/PASSIVE_WANDER
/SCHEDULED

#concept for branching dialog state def
BRANCHING_DIALOG
	0:
	"Would you like a hot dog?"
	(1) "Yes"
	(2) "No"
	1:
	"That's what I thought you would say"
	(3) "Where's my hot dog?" 
	(X) "Actually, forget it." #(X) ends branching dialog
	2:
	"Bullshit"
	#transfers to nested state
	(ALERT_PASSIVE
		passive_text: "Get out of my hot dog store"
		talk_radius: 50
	/ALERT_PASSIVE)
	3:
	"I don't know, how about you buy one?"
	(SHOP
		ITEM("Hot Dog",100)
	/SHOP)
/BRANCHING_DIALOG

#MILESTONE DEF IS FOR A FEW COMPLEX, IMPORTANT CHARACTERS WHO'S NPC DEF CHANGES SIGNIFICANTLY AS THE OVERARCHING GAME PROGRESSES.
#IT CONTAINS NESTED PRIMITIVE+ADVANCED DEFS. IT DETERMINES ACTIVE DEFINITION BY QUERYING A MILESTONE TRACKER OBJECT

MILESTONES_DEF
	first_day:
		(ALERT_PASSIVE
			passive_text: "My hot dogs are too expensive for you."
			talk_radius: 50
		/ALERT_PASSIVE)
	has_100_dollars:
		BRANCHING_DIALOG
		0:
		"Would you like a hot dog?"
		(1) "Yes"
		(2) "No"
		1:
		"That's what I thought you would say"
		(3) "Where's my hot dog?" 
		(X) "Actually, forget it." #(X) ends branching dialog
		2:
		"Bullshit"
		#transfers to nested state
		(ALERT_PASSIVE
			passive_text: "Get out of my hot dog store"
			talk_radius: 50
		/ALERT_PASSIVE)
		3:
		"I don't know, how about you buy one?"
		(SHOP
			ITEM("Hot Dog",100)
		/SHOP)
		/BRANCHING_DIALOG
/MILESTONES_DEF
