### ISSUE TITLE
Writing Milestone 1

### ISSUE THREAD

**Issue by blkilpatrick42** [blkilpatrick42/Jim#11]
- [ ] Menus/UI
- [ ] Environment (location names, signs, etc.)
- [ ] Scripted dialogue sequences (conversations, tutorials, story beats)
- [ ] Incidental dialogue (barks and such from NPCs as you go by them)

**Comment by blkilpatrick42** [comment]
https://twinery.org/

We can use twine during the writing process to lay out the scripts before transcribing them into something machine-readable
