### ISSUE TITLE
Mobster AI Milestone 2

### ISSUE THREAD

**Issue by blkilpatrick42** [blkilpatrick42/Jim#14]
- [x] Branching patrols (patrol points can have multiple next patrol points)
- [x] Out & back patrols: Mobsters will take branching patrols to the end, then return to the main path
- [x] mobsters will acquire the targets of nearby mobsters if there is a line of sight to the target (ie, one mobster notices an intruder and goes alert, nearby mobsters will notice the same intruder)
- [x] will assault and capture areas owned by mobsters of the opposing team
