### ISSUE TITLE
Alpha Game World Milestone 2

### ISSUE THREAD

**Issue by blkilpatrick42** [blkilpatrick42/Jim#18]
- [x] Capturable Labyrinth 2 (abandoned neighborhoods)
- [x] Capturable Labyrinth 3 (abandoned neighborhoods)
- [x] Capturable Labyrinth 4 (abandoned businesses)
- [x] Capturable Labyrinth 5 (abandoned businesses)

**Comment by blkilpatrick42** [comment]
![image](https://github.com/blkilpatrick42/Jim/assets/14854875/4dff1f0e-2ce6-4b7e-aa56-dfc3d38d3cc1)
