### ISSUE TITLE
Mobster AI Milestone 1

### ISSUE THREAD

**Issue by blkilpatrick42** [blkilpatrick42/Jim#4]
- [x] patrol sub-state
- [x] vision cones with ray-tracing
- [x] alert sub-state
- [x] investigate sub-state
- [x] re-orient to find clear shot to target
- [x] path around each other when navigating
- [x] attack enemies
- [x] are drawn to food
- [x] refactor AI state machine for expandability using node composition

**Comment by blkilpatrick42** [comment]
![20240502_084510](https://github.com/blkilpatrick42/Jim/assets/14854875/b48884cc-f560-4577-82de-215e83f465f6)

An example of the "Capturable Labyrinths" which form the basis of "assault and capture" behavior of the Mobster AI.

In this example, the area is controlled by red mobsters, so red mobsters spawn there.

An adjacent blu controlled area will periodically send dudes into this zone to fight red mobsters.

If the AI mobsters take out every red mobster, the area's affiliation will switch to blu, and then blu mobsters will spawn.
