### ISSUE TITLE
Pizza Delivery Milestone 1

### ISSUE THREAD

**Issue by blkilpatrick42** [blkilpatrick42/Jim#5]
- [x] unique pizza physics object
- [x] pizza delivery mission assigned to random destination
- [x] money awarded based on time
- [x] "home base" Pizza restaurant populated with friendly characters
