### ISSUE TITLE
Alpha Game World Milestone 1

### ISSUE THREAD

**Issue by blkilpatrick42** [blkilpatrick42/Jim#6]
- [x] Central Safe area (location of pizza restaurant, apartment)
- [x] Capturable Labyrinth 1 (abandoned neighborhoods)
- [x] Capturable Labyrinth 6 (dockside warehouses)
- [x] Outside City Area 2 (woods)
- [x] Secondary Safe area 2 (upscale beach neighborhood)
- [x] day/night cycle

**Comment by blkilpatrick42** [comment]
![20240519_165740](https://github.com/blkilpatrick42/Jim/assets/14854875/32641287-4d7e-462d-a894-340aa1bd6b29)

Abstracted layout for Alpha Game World, showing zones, relative positions, entrance/exits
