### ISSUE TITLE
Apartment Milestone 2

### ISSUE THREAD

**Issue by blkilpatrick42** [blkilpatrick42/Jim#8]
- [x] player can decorate apartment using items bought with in-game money
- [x] apartment will provide place for player to sleep and speed up game time
- [x] apartment will have calendar marking weeks of in-game time passed ("week 1" "week 2" etc) and day of the week
